from reportlab.platypus import (
    SimpleDocTemplate, Table, TableStyle,
    Paragraph, Spacer
)
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
import os


def create_pdf(df, user_info=None):
    os.makedirs("output", exist_ok=True)
    file_path = "output/diet_plan.pdf"

    doc = SimpleDocTemplate(
        file_path,
        pagesize=A4,
        rightMargin=30,
        leftMargin=30,
        topMargin=30,
        bottomMargin=20
    )

    styles = getSampleStyleSheet()
    elements = []

    # ---------------- TITLE ---------------- #
    title = Paragraph("<b>AI Personalized Diet Plan</b>", styles["Title"])
    elements.append(title)
    elements.append(Spacer(1, 10))

    # ---------------- USER INFO ---------------- #
    if user_info:
        info_text = f"""
        <b>Age:</b> {user_info.get('age', 'N/A')} &nbsp;&nbsp;&nbsp;
        <b>Goal:</b> {user_info.get('goal', 'N/A')} <br/>
        <b>Calories:</b> {user_info.get('calories', 'N/A')} kcal/day
        """
        elements.append(Paragraph(info_text, styles["Normal"]))
        elements.append(Spacer(1, 15))

    # ---------------- TABLE ---------------- #
    def wrap(x):
        return Paragraph(str(x), styles["Normal"])

    data = [df.columns.tolist()]
    for row in df.values.tolist():
        data.append([wrap(i) for i in row])

    table = Table(
        data,
        colWidths=[60, 70, 80, 200, 70]
    )

    style = TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#22c55e")),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),

        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
    ])

    # Alternate rows
    for i in range(1, len(data)):
        if i % 2 == 0:
            style.add('BACKGROUND', (0, i), (-1, i), colors.whitesmoke)

    table.setStyle(style)
    elements.append(table)

    elements.append(Spacer(1, 20))

    footer = Paragraph(
        "Generated by AI Diet Planner • Stay consistent 💪",
        styles["Normal"]
    )
    elements.append(footer)

    doc.build(elements)

    return file_path